#!/bin/bash

clear
javac *.java

java CouncilMember normal
java CouncilMember normal
java CouncilMember normal
java CouncilMember normal
java CouncilMember normal
java CouncilMember normal
java CouncilMember normal
java CouncilMember normal
java CouncilMember normal
java CouncilMember normal

